image: registry.gitlab.com/my-privacy-dns/ci-runner

variables:
  GIT_DEPTH: 5

cache:
  key: ${CI_JOB_NAME}
  paths:
    - $CI_PROJECT_DIR/data/

stages:
  - test
  - build
  - deploy
  #- pages

before_script:
  - printf "Running before script...\n"
  - git config --global user.email "4593890-MypDNS@users.noreply.gitlab.com"
  - git config --global user.name "MypDNS"

after_script:
  - echo "After script section...\n"
  - git remote set-url origin https://mypdns:$MypDNS_CI@gitlab.com/$CI_PROJECT_PATH.git
  - find $CI_PROJECT_DIR/source/ -type f -name '*.list' -exec bash -c "sort -i -u -f '{}' -o '{}' " \;
  - git add .
  - git status
  - git commit -m '[skip ci] commit from CI runner'
  - git push -u origin master

build:
  stage: build
  only:
  - merge_requests
  - master
  script:
    - echo "Building"
    - git checkout -B master
    - find $CI_PROJECT_DIR/source/ -type f -name '*.list' -exec bash -c "sort -i -u -f '{}' -o '{}' " \;
    #- bash $CI_PROJECT_DIR/scripts/build.sh
    #- build cache

test1:
  stage: test
  script:
    - printf "Lint bash code...\n"
    #- reuse build cache
    - bash $CI_PROJECT_DIR/scripts/lint.sh

test2:
  stage: test
  script:
    - printf "Running test 2...\n"
    #- reuse cache
    - bash $CI_PROJECT_DIR/scripts/test2.sh

deploy:
  stage: deploy
  script:
    - echo "Do your deploy here"
    - bash $CI_PROJECT_DIR/scripts/deploy.sh
    #- reuse cache
  only:
  - mater

#pages:
#  stage: deploy
#  script:
#  - echo 'Nothing to do...'
#  artifacts:
#    paths:
#    - public
#  only:
#  - master
